name = "cultus-platform"
compatibility_date = "2024-12-26"
compatibility_flags = ["nodejs_compat"]

main = "./.open-next/worker.js"

[build]
command = "npx @opennextjs/cloudflare build"

# Static assets configuration for Next.js files
[assets]
directory = "./.open-next/assets"

# Custom domains (update with your actual domain)
[[routes]]
pattern = "app.cultuslearn.com/*"
zone_name = "cultuslearn.com"

# Environment variables for production
[vars]
NODE_VERSION = "20"
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

# R2 bucket binding for file storage
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cultus-public-assets"
preview_bucket_name = "cultus-public-assets-preview"

# KV binding for caching (if needed)
[[kv_namespaces]]
binding = "KV_CACHE"
id = ""
preview_id = ""

# Durable Objects (if using real-time features)
# [[durable_objects.bindings]]
# name = "REALTIME_SESSION"
# class_name = "RealtimeSession"

[env.staging]
name = "cultus-platform-staging"
vars = { NODE_ENV = "staging" }

[env.production] 
name = "cultus-platform-production"
vars = { NODE_ENV = "production" }

# Resource limits
[limits]
cpu_ms = 30000 